version: '3.1'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      DATABASE:
      USER:
      MYSQL_ROOT_PASSWORD:
      HOST: db
      TOKEN_SECRET:
    volumes:
      - './src/:/src/src/:ro'
  db:
    image: mysql
    restart: always
    environment:
      DATABASE:
      MYSQL_ROOT_PASSWORD:
      HOST:
    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
volumes:
  api_data:
