name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TOKEN_SECRET: token_secret
      MYSQL_ROOT_PASSWORD: password
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.Js
        uses: actions/setup-node@v2

      - name: Prep environment .env
        run: |
          cp .env.example .env
          sed s/TOKEN_SECRET=/TOKEN_SECRET=$TOKEN_SECRET/ -i .env
          sed s/MYSQL_ROOT_PASSWORD=/MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD/ -i .env

      - name: Connect to the database
        run: docker-compose up --detach db

      - name: Install dependencies
        run: yarn install

      - name: Run the tests
        run: yarn test
